//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssemblyVisualizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssemblyVisualizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Browser.
        /// </summary>
        internal static string AssemblyBrowser {
            get {
                return ResourceManager.GetString("AssemblyBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Search.
        /// </summary>
        internal static string BackToSearch {
            get {
                return ResourceManager.GetString("BackToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate back.
        /// </summary>
        internal static string CannotNavigateBack {
            get {
                return ResourceManager.GetString("CannotNavigateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate forward.
        /// </summary>
        internal static string CannotNavigateForward {
            get {
                return ResourceManager.GetString("CannotNavigateForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorize.
        /// </summary>
        internal static string Colorize {
            get {
                return ResourceManager.GetString("Colorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decolorize.
        /// </summary>
        internal static string Decolorize {
            get {
                return ResourceManager.GetString("Decolorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descendants count.
        /// </summary>
        internal static string DescendantsCount {
            get {
                return ResourceManager.GetString("DescendantsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        internal static string Enums {
            get {
                return ResourceManager.GetString("Enums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Graph.
        /// </summary>
        internal static string FillGraph {
            get {
                return ResourceManager.GetString("FillGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaces.
        /// </summary>
        internal static string Interfaces {
            get {
                return ResourceManager.GetString("Interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members count.
        /// </summary>
        internal static string MembersCount {
            get {
                return ResourceManager.GetString("MembersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Size.
        /// </summary>
        internal static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override from.
        /// </summary>
        internal static string OverrideFrom {
            get {
                return ResourceManager.GetString("OverrideFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in Graph.
        /// </summary>
        internal static string SearchInGraph {
            get {
                return ResourceManager.GetString("SearchInGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value types.
        /// </summary>
        internal static string ValueTypes {
            get {
                return ResourceManager.GetString("ValueTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual.
        /// </summary>
        internal static string Virtual {
            get {
                return ResourceManager.GetString("Virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
    }
}
